name: Request Project Tests Grade
description: 📒 Request a project tests grade.
title: Request Project Tests Grade
labels: ["grade-tests"]

body:
  - type: markdown
    attributes:
      value: |
        Use this issue to request a project tests grade.

  - type: input
    id: full_name
    attributes:
      label: Full Name
      description: Please enter your full name.
      placeholder: Full Name
    validations:
      required: true

  - type: input
    id: usf_email
    attributes:
      label: USF Email
      description: Please enter your USF email address.
      placeholder: username@dons.usfca.edu
    validations:
      required: true

  - type: input
    id: project_release
    attributes:
      label: Release
      description: Please enter the project release for your test grade.
      placeholder: v1.0.0
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        :warning: If you already have an issue created for this grade, please edit and re-open that issue rather than create a new one!
